apiVersion: v1
kind: Service
metadata:
  name: my-react-app-service
  namespace: my-react-app
  # labels:
  #   app: react-app
spec:
  type: LoadBalancer
  selector:
    app: react-app
  ports:
    # - protocol: TCP
    - name: my-app
      port: 3200
      targetPort: 3000
      # nodePort: 30008